Rails.application.routes.draw do

  get 'bingo_sites/sky_bingo'
  get 'bingo_sites/bet365_bingo'
  get 'bingo_sites/lippy_bingo'
  get 'bingo_sites/glossy_bingo'
  get 'bingo_sites/robin_hood_bingo'
  get 'bingo_sites/coral_bingo'
  get 'bingo_sites/ladbrokes_bingo'
  get 'bingo_sites/sun_bingo'
  get 'bingo_sites/bgo_bingo'
  get 'bingo_sites/paddy_power_bingo'

  get 'sports_sites/betway'
  get 'sports_sites/william_hill'
  get 'sports_sites/_888_sport'
  get 'sports_sites/pinnacle_sports'
  get 'sports_sites/unibet'
  get 'sports_sites/paddy_power'
  get 'sports_sites/betfred'
  get 'sports_sites/bet_victor'
  get 'sports_sites/ladbrokes'
  get 'sports_sites/tipico'

  get 'casino_sites/_888_casino'
  get 'casino_sites/mansion_casino'
  get 'casino_sites/royal_panda'
  get 'casino_sites/_32red'
  get 'casino_sites/grosvenor_casinos'
  get 'casino_sites/casumo'
  get 'casino_sites/leo_vegas'
  get 'casino_sites/betway_casino'
  get 'casino_sites/bet_victor'
  get 'casino_sites/netbet_casino'

  get 'live_casino_sites/_888_casino'
  get 'live_casino_sites/mansion_casino'
  get 'live_casino_sites/casumo'
  get 'live_casino_sites/netbet_casino'
  get 'live_casino_sites/royal_panda'
  get 'live_casino_sites/_32red'
  get 'live_casino_sites/bet_victor'
  get 'live_casino_sites/betway_casino'
  get 'live_casino_sites/grosvenor_casinos'
  get 'live_casino_sites/intercasino'

  get 'slot_sites/play_sunny'
  get 'slot_sites/spin_rider'
  get 'slot_sites/spinit'
  get 'slot_sites/sloty'
  get 'slot_sites/starspins'
  get 'slot_sites/videoslots'
  get 'slot_sites/casimba'
  get 'slot_sites/spin_and_win'
  get 'slot_sites/slot_planet'
  get 'slot_sites/casino_heroes'

  get 'corporate/about'
  get 'corporate/contact'
  get 'corporate/terms'
  get 'corporate/privacy'
  get 'corporate/responsible'
  get 'corporate/sitemap'

  get 'slots/best'
  get 'slots/new'
  get 'slots/all'
  get 'slots/rules'

  get 'live_casino/best'
  get 'live_casino/new'
  get 'live_casino/all'
  get 'live_casino/rules'

  get 'casino/best'
  get 'casino/new'
  get 'casino/all'
  get 'casino/rules'

  get 'sports/best'
  get 'sports/new'
  get 'sports/all'
  get 'sports/rules'

  get 'bingo/best'
  get 'bingo/new'
  get 'bingo/all'
  get 'bingo/rules'

  get 'slots', to: 'pages#slots'
  get 'live_casino', to: 'pages#live_casino'
  get 'casino', to: 'pages#casino'
  get 'sports', to: 'pages#sports'
  get 'bingo', to: 'pages#bingo'
  get 'best_offers', to: 'pages#best_offers'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end
